import type { RawPlantData } from "./plantAdapter";

export const plantsData: RawPlantData[] = [
	{
		name: "Monstera Deliciosa",
		light: "Bright indirect",
		water: "Every 7 days",
		petSafe: "No",
		category: "statement",
		modelName: "monstera",
	},
	{
		name: "Snake Plant",
		light: "Low to bright",
		water: "Every 14 days",
		petSafe: "No",
		category: "low-light",
		modelName: "snake-plant",
	},
	{
		name: "Calathea Orbifolia",
		light: "Medium indirect",
		water: "Every 5 days",
		petSafe: "Yes",
		category: "humidity",
		modelName: "calathea-orbifolia",
	},
	{
		name: "Pothos Neon",
		light: "Low to medium",
		water: "Every 8 days",
		petSafe: "No",
		category: "hanging",
		modelName: "pothos-neon",
	},
	{
		name: "Areca Palm",
		light: "Bright filtered",
		water: "Every 6 days",
		petSafe: "Yes",
		category: "air-purifying",
		modelName: "areca-palm",
	},
	{
		name: "ZZ Plant",
		light: "Low light",
		water: "Every 18 days",
		petSafe: "No",
		category: "low-light",
		modelName: "zz-plant",
	},
	{
		name: "Spider Plant",
		light: "Medium indirect",
		water: "Every 7 days",
		petSafe: "Yes",
		category: "pet-safe",
		modelName: "spider-plant",
	},
	{
		name: "Peace Lily",
		light: "Low to medium",
		water: "Every 7 days",
		petSafe: "No",
		category: "low-light",
		modelName: "peace-lily",
	},
	{
		name: "Chinese Evergreen",
		light: "Low to medium",
		water: "Every 8 days",
		petSafe: "No",
		category: "low-light",
		modelName: "chinese-evergreen",
	},
	{
		name: "Haworthia",
		light: "Bright indirect",
		water: "Every 21 days",
		petSafe: "Yes",
		category: "pet-safe",
		modelName: "haworthia",
	},
	{
		name: "Phalaenopsis Orchid",
		light: "Bright indirect",
		water: "Every 7 days",
		petSafe: "Yes",
		category: "pet-safe",
		modelName: "phalaenopsis-orchid",
	},
	{
		name: "Bamboo Palm",
		light: "Bright filtered",
		water: "Every 7 days",
		petSafe: "Yes",
		category: "air-purifying",
		modelName: "bamboo-palm",
	},
	{
		name: "Rubber Plant",
		light: "Bright indirect",
		water: "Every 10 days",
		petSafe: "No",
		category: "air-purifying",
		modelName: "rubber-plant",
	},
	{
		name: "Aloe Vera",
		light: "Bright direct",
		water: "Every 21 days",
		petSafe: "No",
		category: "air-purifying",
		modelName: "aloe-vera",
	},
	{
		name: "Chrysanthemum",
		light: "Bright indirect",
		water: "Every 4 days",
		petSafe: "No",
		category: "air-purifying",
		modelName: "chrisanthemum",
	},
	{
		name: "Eastern Grey",
		light: "Medium indirect",
		water: "Every 5 days",
		petSafe: "Yes",
		category: "hanging",
		modelName: "eastern-grey",
	},
	{
		name: "Fiddle Leaf Fig",
		light: "Bright indirect",
		water: "Every 7 days",
		petSafe: "No",
		category: "statement",
		modelName: "fiddle-leaf-fig",
	},
	{
		name: "Banana Plant",
		light: "Bright direct",
		water: "Every 5 days",
		petSafe: "Yes",
		category: "statement",
		modelName: "banana-plant",
	},
	{
		name: "Maidenhair Fern",
		light: "Medium indirect",
		water: "Every 3 days",
		petSafe: "Yes",
		category: "humidity",
		modelName: "maidenhair-fern",
	},
];
