import type { RawPlantData } from "./plantAdapter";

export const plantsData: RawPlantData[] = [
	{
		name: "Monstera Deliciosa",
		light: "Bright indirect",
		water: "Every 7 days",
		petSafe: "No",
		category: "statement",
		modelName: "monstera",
		price: 42.99,
		discount: 20,
	},
	{
		name: "Snake Plant",
		light: "Low to bright",
		water: "Every 14 days",
		petSafe: "No",
		category: "low-light",
		modelName: "snake-plant",
		price: 24.99,
	},
	{
		name: "Calathea Orbifolia",
		light: "Medium indirect",
		water: "Every 5 days",
		petSafe: "Yes",
		category: "humidity",
		modelName: "calathea-orbifolia",
		price: 36.5,
		discount: 15,
	},
	{
		name: "Pothos Neon",
		light: "Low to medium",
		water: "Every 8 days",
		petSafe: "No",
		category: "hanging",
		modelName: "pothos-neon",
		price: 21.0,
	},
	{
		name: "Areca Palm",
		light: "Bright filtered",
		water: "Every 6 days",
		petSafe: "Yes",
		category: "air-purifying",
		modelName: "areca-palm",
		price: 39.99,
		discount: 10,
	},
	{
		name: "ZZ Plant",
		light: "Low light",
		water: "Every 18 days",
		petSafe: "No",
		category: "low-light",
		modelName: "zz-plant",
		price: 31.49,
	},
	{
		name: "Spider Plant",
		light: "Medium indirect",
		water: "Every 7 days",
		petSafe: "Yes",
		category: "pet-safe",
		modelName: "spider-plant",
		price: 19.99,
	},
	{
		name: "Peace Lily",
		light: "Low to medium",
		water: "Every 7 days",
		petSafe: "No",
		category: "low-light",
		modelName: "peace-lily",
		price: 28.0,
		discount: 12,
	},
	{
		name: "Chinese Evergreen",
		light: "Low to medium",
		water: "Every 8 days",
		petSafe: "No",
		category: "low-light",
		modelName: "chinese-evergreen",
		price: 29.99,
	},
	{
		name: "Haworthia",
		light: "Bright indirect",
		water: "Every 21 days",
		petSafe: "Yes",
		category: "pet-safe",
		modelName: "haworthia",
		price: 14.5,
	},
	{
		name: "Phalaenopsis Orchid",
		light: "Bright indirect",
		water: "Every 7 days",
		petSafe: "Yes",
		category: "pet-safe",
		modelName: "phalaenopsis-orchid",
		price: 33.75,
		discount: 18,
	},
	{
		name: "Bamboo Palm",
		light: "Bright filtered",
		water: "Every 7 days",
		petSafe: "Yes",
		category: "air-purifying",
		modelName: "bamboo-palm",
		price: 37.2,
	},
	{
		name: "Rubber Plant",
		light: "Bright indirect",
		water: "Every 10 days",
		petSafe: "No",
		category: "air-purifying",
		modelName: "rubber-plant",
		price: 34.99,
	},
	{
		name: "Aloe Vera",
		light: "Bright direct",
		water: "Every 21 days",
		petSafe: "No",
		category: "air-purifying",
		modelName: "aloe-vera",
		price: 16.99,
	},
	{
		name: "Chrysanthemum",
		light: "Bright indirect",
		water: "Every 4 days",
		petSafe: "No",
		category: "air-purifying",
		modelName: "chrisanthemum",
		price: 22.49,
		discount: 25,
	},
	{
		name: "Eastern Grey",
		light: "Medium indirect",
		water: "Every 5 days",
		petSafe: "Yes",
		category: "hanging",
		modelName: "eastern-grey",
		price: 18.99,
	},
	{
		name: "Fiddle Leaf Fig",
		light: "Bright indirect",
		water: "Every 7 days",
		petSafe: "No",
		category: "statement",
		modelName: "fiddle-leaf-fig",
		price: 45.0,
		discount: 8,
	},
	{
		name: "Banana Plant",
		light: "Bright direct",
		water: "Every 5 days",
		petSafe: "Yes",
		category: "statement",
		modelName: "banana-plant",
		price: 41.25,
	},
	{
		name: "Maidenhair Fern",
		light: "Medium indirect",
		water: "Every 3 days",
		petSafe: "Yes",
		category: "humidity",
		modelName: "maidenhair-fern",
		price: 27.5,
		discount: 10,
	},
];
